### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by dembanakh** [vgzowski/slavic-ride#11]
These are just small (not too important) suggestions. You don't have to apply them if you have a good reason not to, or even if you just don't like them😃

---

https://github.com/vgzowski/slavic-ride/blob/056feb57803b8d1506f05071b742f45623777f8e/slavic-ride-java/src/main/java/Slavic/Ride/MMM/User/Driver.java#L21
Can this be `boolean` instead of `Boolean`? Primitive types should be preferred whenever possible

---

https://github.com/vgzowski/slavic-ride/blob/056feb57803b8d1506f05071b742f45623777f8e/slavic-ride-java/src/main/java/Slavic/Ride/MMM/Service/DriverService.java#L66-L73
Don't invent the wheel :)
```java
drivers.stream.min((d1, d2) ->
    Utils.calculateDistance(location, d1.getLocation()) - Utils.calculateDistance(location, d2.getLocation()));
```

**Comment by Bliznetc** [comment]
1. We have an error with DB when using primitive type.

2. Will be modified soon
